### ISSUE TITLE
[Bug]: i remember there is a heart icon on the bottom right, showing what versions we are at.... it is missing somehow 

### ISSUE THREAD

**Issue by bryanray** [anapnoe/stable-diffusion-webui-ux#25]
### Is there an existing issue for this?

[Bug]: i remember there is a heart icon on the bottom right, showing what versions we are at.... it is missing somehow

**Comment by anapnoe** [comment]
not missing anything you probably install some incompatible extension that messed your ui disable all non inbuild extensions and reload the ui then enable them one by one to see what caused the issue 
The current repo will not update to an unstable release from master yet until main issues are resolved
master does not provide any versioning system with the extensions so if you try to install the latest extension from extensions panel inside the ui, it will download the latest release which is incompatible with the previous stable releases in order to make it work you need to go to the extension repository and download the previous commit of that extension, download and extract it in the extensions folder if the one you download doesn't work either then go and repeat the process until you find the one that works

**Comment by bryanray** [comment]
i know update ext will not fit the old gradio version, 

and also i know webui do not have version control sys on their side

dont bother, maybe i am hallucinating 

https://github.com/anapnoe/stable-diffusion-webui-ux/issues/24
would you look at it, i make some change to it

**Comment by bryanray** [comment]
![image](https://user-images.githubusercontent.com/1768531/229223387-1eeca06a-67c1-4dfb-8e25-f98871c8252b.jpeg)

**Comment by bryanray** [comment]
![image](https://user-images.githubusercontent.com/1768531/229223518-70fcb8d8-0545-4f1b-bb38-befdddbaad1b.jpeg)
