### ISSUE TITLE
[Feature Request]: Live previews the same size as output

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The live previews are small and the final image is large. To have the image zooming in and out when generating can be jarring. Would it be possible to have the live previews scaled to the size of the final image?

### Proposed workflow

1. No workflow.

**Comment by anapnoe** [comment]
already exists for live preview 
go to settings live previews - Image creation progress preview mode 
you can select - full instead of an approximation method
also you can select 
Live preview image fit method - contain (this applies to any mode full or approximation)
for the final image go to settings - ui
Generated image fit method - contain

**Comment by MakingMadness** [comment]
Setting to "contain" did the trick, thanks!
